enableGlobalCache: true

logFilters:
  - code: YN0032
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": ^4.9.1
  "@svgr/core@*":
    peerDependencies:
      "@babel/core": ^7.1.6
  psl@*:
    dependencies:
      punycode: ^2.1.1
  react-native@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
