name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        shard: ['1/4', '2/4', '3/4', '4/4']
    name: Node v${{ matrix.node-version }} on ${{ inputs.os }} (${{ matrix.shard }})
    runs-on: ${{ inputs.os }}
    env:
      # NB(rwx): checking out as jest-abq does not mesh well with upstream's tests.
      GITHUB_WORKSPACE: /home/runner/work/jest-abq/jest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: build
        run: yarn build:js
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: run tests
        run: yarn test-ci-partial:parallel --max-workers ${{ steps.cpu-cores.outputs.count }} --shard=${{ matrix.shard }}

  test-jasmine:
    strategy:
      fail-fast: false
      matrix:
        shard: ['1/4', '2/4', '3/4', '4/4']
    name: Node LTS on ${{ inputs.os }} using jest-jasmine2 (${{ matrix.shard }})
    runs-on: ${{ inputs.os }}
    env:
      # NB(rwx): checking out as jest-abq does not mesh well with upstream's tests.
      GITHUB_WORKSPACE: /home/runner/work/jest-abq/jest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: build
        run: yarn build:js
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: run tests using jest-jasmine
        run: yarn jest-jasmine-ci --max-workers ${{ steps.cpu-cores.outputs.count }} --shard=${{ matrix.shard }}
